name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential cmake pkg-config libsdl2-dev libgl1-mesa-dev

    - name: configure
      run: cmake -S . -B build

    - name: build
      run: cmake --build build
